# Copyright 2026 Code Capsules
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: v2
name: mysql-operator
description: A helm chart for Code Capsules Operator for MySQL
appVersion: 'latest'
kubeVersion: '>= 1.19.0-0'
keywords:
  - mysql
  - percona
  - orchestrator
  - codecapsules
  - database
version: 0.0.0
home: https://codecapsules.io/
sources:
  - https://github.com/codecapsules-io/mysql-operator.git
annotations:
  artifacthub.io/license: 'Apache-2.0'
  artifacthub.io/operator: 'true'
  artifacthub.io/operatorCapabilities: 'full lifecycle'
  artifacthub.io/images: |
    - name: mysql-operator
      image: docker.io/codecapsules-io/mysql-operator:latest
      whitelisted: true
    - name: orchestrator
      image: docker.io/codecapsules-io/mysql-operator-orchestrator:latest
      whitelisted: true
    - name: mysql-5.7-sidecar
      image: docker.io/codecapsules-io/mysql-operator-sidecar-5.7:latest
      whitelisted: true
    - name: mysql-8.0-sidecar
      image: docker.io/codecapsules-io/mysql-operator-sidecar-8.0:latest
      whitelisted: true
  artifacthub.io/crds: |
    - kind: MySQLCluster
      version: v1alpha1
      name: mysqlclusters.mysql.presslabs.org
      displayName: MySQLCluster
      description: Represents a MySQL cluster managed by Code Capsules Operator for MySQL.
  artifacthub.io/crdsExamples: |
    - apiVersion: v1alpha1
      kind: MysqlCluster
      metadata:
        name: my-cluster
      spec:
        replicas: 3
        secretName: my-secret
      mysqlConf:
         innodb-buffer-size: 128M
      targetSLO:
        maxSlaveLatency: 10s
