{{- if .Values.mysqlVersionCatalog.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mysql-operator.fullname" . }}-mysql-versions
  labels:
    {{- include "mysql-operator.labels" . | nindent 4 }}
data:
  {{ .Values.mysqlVersionCatalog.fileName }}: |
{{- range $k, $v := .Values.mysqlVersionCatalog.data }}
    {{ $k }}={{ $v }}
{{- end }}
{{- end }}
