# Copyright 2026 Code Capsules
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: v1
kind: Secret
metadata:
  name: mysql-operator-orc
  labels:
    app.kubernetes.io/name: mysql-operator
    app.kubernetes.io/version: v0.7.0
data:
  TOPOLOGY_USER: b3JjaGVzdHJhdG9y
  TOPOLOGY_PASSWORD: OWtrTlZQQmZTZg==
