#!/usr/bin/env bash
# Copyright 2026 Code Capsules
# SPDX-License-Identifier: Apache-2.0
#
# Sync CRDs from config/crd/bases into deploy/manifests/<version>/crds/.
# Operator manifests under deploy/manifests/<version>/operator/ are maintained
# manually (copy an existing version directory and edit image tags, args, etc.).
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CRD_SRC="${ROOT_DIR}/config/crd/bases"

VERSION="${1:-${VERSION:-}}"
if [[ -z "${VERSION}" ]]; then
  VERSION="$(cd "${ROOT_DIR}" && make --no-print-directory version)"
fi
if [[ "${VERSION}" != v* ]]; then
  VERSION="v${VERSION}"
fi

MANIFEST_DIR="${ROOT_DIR}/deploy/manifests/${VERSION}"
CRD_DIR="${MANIFEST_DIR}/crds"
YQ_BIN="${YQ:-yq}"

if ! command -v "${YQ_BIN}" >/dev/null 2>&1; then
  echo "yq is required (install via 'make build.tools' or set YQ=...)" >&2
  exit 1
fi

echo "Syncing CRDs for ${VERSION} -> ${CRD_DIR}"

(cd "${ROOT_DIR}" && make --no-print-directory kubebuilder.manifests)

if [[ ! -d "${MANIFEST_DIR}/operator" ]]; then
  echo "warning: ${MANIFEST_DIR}/operator/ does not exist." >&2
  echo "         Copy deploy/manifests/v0.7.0/operator/ to ${MANIFEST_DIR}/operator/ and edit for the new release." >&2
fi

rm -rf "${CRD_DIR}"
mkdir -p "${CRD_DIR}"

shopt -s nullglob
crd_files=("${CRD_SRC}"/*.yaml)
if [[ ${#crd_files[@]} -eq 0 ]]; then
  echo "no CRDs found in ${CRD_SRC}; run 'make kubebuilder.manifests' first" >&2
  exit 1
fi

crd_resources=()
for crd in "${crd_files[@]}"; do
  base="$(basename "${crd}")"
  dest="${CRD_DIR}/${base}"
  if head -n 5 "${crd}" | grep -q 'SPDX-License-Identifier'; then
    cp "${crd}" "${dest}"
  else
    {
      echo '# Copyright 2026 Code Capsules'
      echo '# SPDX-License-Identifier: Apache-2.0'
      echo '#'
      cat "${crd}"
    } >"${dest}"
  fi
  "${YQ_BIN}" e '.metadata.labels["app.kubernetes.io/name"]="mysql-operator"' -i "${dest}"
  "${YQ_BIN}" e 'del(.metadata.creationTimestamp)' -i "${dest}"
  "${YQ_BIN}" e 'del(.status)' -i "${dest}"
  crd_resources+=("  - ${base}")
done

cat >"${CRD_DIR}/kustomization.yaml" <<EOF
# Copyright 2026 Code Capsules
# SPDX-License-Identifier: Apache-2.0
#
# Generated by hack/generate-deploy-manifests.sh — do not edit by hand.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
$(printf '%s\n' "${crd_resources[@]}")
EOF

if [[ ! -f "${MANIFEST_DIR}/kustomization.yaml" ]]; then
  cat >"${MANIFEST_DIR}/kustomization.yaml" <<'EOF'
# Copyright 2026 Code Capsules
# SPDX-License-Identifier: Apache-2.0
#
# Apply CRDs before upgrading operator workloads across major/minor releases.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - crds
  - operator
EOF
fi

echo "Wrote:"
echo "  ${CRD_DIR}/ ($((${#crd_files[@]})) CRDs)"
if [[ -d "${MANIFEST_DIR}/operator" ]]; then
  echo "  ${MANIFEST_DIR}/operator/ (unchanged — maintained manually)"
fi
