# Copyright 2026 Code Capsules
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlCluster
metadata:
  name: my-cluster
spec:
  replicas: 2
  secretName: my-secret
  mysqlVersion: "8.4"
