# Copyright 2026 Code Capsules
# SPDX-License-Identifier: Apache-2.0
#
# NOTE: this image is for development only
# Copy the mysql-operator-sidecar into its own image


###############################################################################
#  Build rclone
###############################################################################

FROM debian:stretch as rclone

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        gnupg ca-certificates wget unzip

COPY hack/docker/rclone.gpg /root/rclone.gpg
RUN gpg --import /root/rclone.gpg

ENV RCLONE_VERSION=1.57.0

RUN wget -nv https://github.com/ncw/rclone/releases/download/v${RCLONE_VERSION}/rclone-v${RCLONE_VERSION}-linux-amd64.zip \
    && wget -nv https://github.com/ncw/rclone/releases/download/v${RCLONE_VERSION}/SHA256SUMS \
    && gpg --verify --output=- SHA256SUMS > sums \
    && sha256sum -c --ignore-missing sums \
    && unzip rclone-*-linux-amd64.zip \
    && mv rclone-*-linux-amd64/rclone /usr/local/bin/ \
    && chmod 755 /usr/local/bin/rclone


###############################################################################
#  Docker image for sidecar containers
###############################################################################

FROM debian:bullseye-slim as sidecar

RUN groupadd -g 999 mysql
RUN useradd -u 999 -r -g 999 -s /sbin/nologin \
    -c "Default Application User" mysql

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        apt-transport-https ca-certificates pigz wget \
    && rm -rf /var/lib/apt/lists/*

ARG XTRABACKUP_PKG=percona-xtrabackup-80
RUN wget -nv -O /tmp/percona-release.deb https://repo.percona.com/apt/percona-release_latest.generic_all.deb \
    && apt-get install -y --no-install-recommends /tmp/percona-release.deb \
    && rm -f /tmp/percona-release.deb \
    && case "${XTRABACKUP_PKG}" in \
        percona-xtrabackup-24) PXB_REPO=pxb-24 ;; \
        percona-xtrabackup-80) PXB_REPO=pxb-80 ;; \
        percona-xtrabackup-84) PXB_REPO=pxb-84-lts ;; \
        *) echo "unsupported XTRABACKUP_PKG=${XTRABACKUP_PKG}" >&2; exit 1 ;; \
    esac \
    && percona-release disable all \
    && percona-release enable pt release \
    && percona-release enable "${PXB_REPO}" release \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
        'percona-toolkit>=3.7.0' ${XTRABACKUP_PKG} unzip default-mysql-client

USER mysql

# set expiration time for dev images
# https://support.coreos.com/hc/en-us/articles/115001384693-Tag-Expiration
LABEL quay.expires-after=2d

COPY --from=rclone /usr/local/bin/rclone /usr/local/bin/rclone
COPY ./hack/docker/sidecar-entrypoint.sh /usr/local/bin/sidecar-entrypoint.sh
COPY ./bin/mysql-operator-sidecar_linux_amd64 /usr/local/bin/mysql-operator-sidecar

ENTRYPOINT ["/usr/local/bin/sidecar-entrypoint.sh"]
