# Copyright 2026 Code Capsules
# SPDX-License-Identifier: Apache-2.0
#
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql-operator
  labels:
    app.kubernetes.io/name: mysql-operator
    app.kubernetes.io/version: v0.6.3
