# Copyright 2026 Code Capsules
# SPDX-License-Identifier: Apache-2.0
#
name: Go Tests

on:
  workflow_dispatch:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: true

      - name: Run unit tests
        env:
          CI: 'true'
          ACK_GINKGO_DEPRECATIONS: '1.16.4'
        run: make test
