# Copyright 2026 Code Capsules
# SPDX-License-Identifier: Apache-2.0
#
name: License Check

on:
  push:
    branches: ['**']

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run license check
        run: ./hack/license-check
