name: Go Tests

on:
  push:
    branches: ["feat/8.4-support"] # runs on push to any branch
  pull_request:
    branches: ["feat/8.4-support"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22" # change to your Go version

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test ./...
